version: '3.8'
services:
  opensearch-agent:
    image: tanminkwan/wta-miniagent:latest
    container_name: opensearch-agent
    ports:
      - 8381:5000
    environment:
      DEBUG: true
      RUN_TYPE: "SERVICE"
      AGENT_NAME: "opensearch_agent"
      AGENT_ROLES: "opensearch_agent"
      MESSAGE_RECEIVER_ENABLED :  false
      ZIPKIN_DOMAIN_NAME: 172.17.0.1
      ZIPKIN_PORT: 9411
      ELASTIC_SEARCH_DOMAIN_NAME: 172.17.0.1
      ELASTIC_SEARCH_PORT: 9200
  config-map:
    image: tanminkwan/wta-miniagent:latest
    container_name: config-map
    ports:
      - 8382:5000
    environment:
      DEBUG: true
      RUN_TYPE: "SERVICE"
      AGENT_NAME: "config_map"
      AGENT_ROLES: "config_map"
      MESSAGE_RECEIVER_ENABLED :  false
      ZIPKIN_DOMAIN_NAME: 172.17.0.1
      ZIPKIN_PORT: 9411
  game-manager:
    image: tanminkwan/wta-miniagent:latest
    container_name: game-manager
    ports:
      - 8383:5000
    depends_on:
      - config-map
    links:
      - opensearch-agent
      - config-map
    environment:
      DEBUG: true
      RUN_TYPE: "SERVICE"
      AGENT_NAME: "game_manager"
      AGENT_ROLES: "game_manager"
      MESSAGE_RECEIVER_ENABLED :  true
      ZIPKIN_DOMAIN_NAME: 172.17.0.1
      ZIPKIN_PORT: 9411
      KAFKA_BOOTSTRAP_SERVERS: "172.17.0.1:9092"
      ELASTICSEARCH_AGENT_SERVICE_ADDRESS: "opensearch-agent:5000"
      CONFIG_MAP_SERVICE_ADDRESS: "config-map:5000"
  service-manager:
    image: tanminkwan/wta-miniagent:latest
    container_name: service-manager
    depends_on:
      - config-map
    links:
      - config-map
    environment:
      DEBUG: true
      RUN_TYPE: "SERVICE"
      AGENT_NAME: "service_manager"
      AGENT_ROLES: "service_manager"
      MESSAGE_RECEIVER_ENABLED :  true
      ZIPKIN_DOMAIN_NAME: 172.17.0.1
      ZIPKIN_PORT: 9411
      KAFKA_BOOTSTRAP_SERVERS: "172.17.0.1:9092"
      CONFIG_MAP_SERVICE_ADDRESS: "config-map:5000"
      K8S_AGENT_SERVICE_ADDRESS: "172.17.0.1:5013"
  betting-booth:
    image: tanminkwan/wta-miniagent:latest
    container_name: betting-booth
    ports:
      - 8384:5000
    environment:
      DEBUG: true
      RUN_TYPE: "SERVICE"
      AGENT_NAME: "betting_booth"
      AGENT_ROLES: "betting_booth"
      MESSAGE_RECEIVER_ENABLED :  true
      ZIPKIN_DOMAIN_NAME: 172.17.0.1
      ZIPKIN_PORT: 9411
      KAFKA_BOOTSTRAP_SERVERS: "172.17.0.1:9092"
